server:
  port: 2333
spring:
  application:
    name: tstjpa

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springjpademo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


